[package]
name = "mmatamm-backtest"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
flexi_logger = "0.29"
float_eq = "1.0"
mmatamm-interface = { git = "https://github.com/mmatamm/mmatamm-interface.git", version = "0.1.0" }
tabled = "0.16" # TODO: Make this optional
postgres = { version = "0.19", features = ["with-chrono-0_4"] }
ahash = "0.8"
hdf5 = { package="hdf5-metno", version = "0.10", features = ["blosc-lz4", "static"] }
ndarray = "0.16"
thiserror = "2.0"
papaya = "0.2.1"
